<table id="mygames">
    <th></th>
<?php
if(is_array($this->myGames)) {
    foreach($this->myGames as $game) {
        $url = $this->url(array('controller'=>'gameload', 'action'=>'load', 'gameId'=>$game['gameId']));
        echo '<tr id="gid'.$game['gameId'].'" onclick="'.$url.'">
        <td><a href="'.$url.'">Load '.$game['gameId'].' '.$game['begin'].'</a></td>
        <td><a href="'.$url.'">'.$game['numberOfPlayers'].'</a></td>
        <td><a href="'.$url.'">'.$game['turnNumber'].'</a></td>
        </tr>';
    }
}
?>
</table>

<a href="<?php echo $this->url(array('controller'=>'index', 'gameId'=>null)) ?>">Back</a>
