<h2>Map editor</h2>
<div class="table">
<table>
    <th>Map name</th><th>Width</th><th>Height</th><th>Map author</th><th>Creation date</th>
<?php
if(is_array($this->mapList)){
    foreach($this->mapList as $map){
        $url = $this->url(array('controller'=>'editor', 'action'=>'edit', 'mapId'=>$map['mapId']));
        echo '<tr id="gid'.$map['mapId'].'" onclick="'.$url.'" class="trlink">
        <td><a href="'.$url.'">'.$map['name'].'</a></td>
        <td><a href="'.$url.'">'.$map['mapWidth'].'</a></td>
        <td><a href="'.$url.'">'.$map['mapHeight'].'</a></td>
        </tr>';
    }
}
?>
    </table>
</div>
<ul>
    <li>
        <a class="button" href="<?php echo $this->url(array('controller' => 'index', 'gameId' => null)) ?>">< Back</a>
    </li>
    <li>
        <a class="button" href="<?php echo $this->url(array('controller' => 'editor', 'action' => 'create')) ?>">Create</a>
    </li>
</ul>