<table id="main" cellspacing="20px">
<!--    <tr>-->
<!--        <td>-->
<!--            <img src="--><?php //echo $this->baseUrl(); ?><!--/img/admin/onas.png"/>-->
<!--            <a href="/admin/onas" >O&nbsp;nas</a>-->
<!--        </td>-->
<!--        <td>-->
<!--            <img src="--><?php //echo $this->baseUrl(); ?><!--/img/admin/portfolio.png"/>-->
<!--            <a href="/admin/portfolio" >Portfolio</a>-->
<!--        </td>-->
<!--        <td>-->
<!--            <img src="--><?php //echo $this->baseUrl(); ?><!--/img/admin/oferta.png"/>-->
<!--            <a href="--><?php //echo $this->url(array('controller' => 'oferta')) ?><!--" >Oferta</a>-->
<!--        </td>-->
<!--        <td>-->
<!--            <img src="--><?php //echo $this->baseUrl(); ?><!--/img/admin/kontakt.png"/>-->
<!--            <a href="/admin/kontakt" >Kontakt</a>-->
<!--        </td>-->
<!--    </tr>-->
    <tr>
        <td>
            <img src="<?php echo $this->baseUrl(); ?>/img/admin/administratorzy.png"/>
            <a href="/admin/player" >Player</a>
        </td>
        <td>
            <img src="<?php echo $this->baseUrl(); ?>/img/admin/castles.png"/>
            <a href="/admin/castle" >Castle</a>
        </td>
    </tr>
</table>