<table id="main" cellspacing="20px">
    <tr>
        <td>
            <img src="<?php echo $this->baseUrl(); ?>/img/admin/administratorzy.png"/>
            <a href="/admin/player" >Player</a>
        </td>
        <td>
            <img src="<?php echo $this->baseUrl(); ?>/img/admin/unit.png"/>
            <a href="/admin/unit" >Unit</a>
        </td>
        <td>
            <img src="<?php echo $this->baseUrl(); ?>/img/admin/language.png"/>
            <a href="/admin/language" >Language</a>
        </td>
        <td>
            <img src="<?php echo $this->baseUrl(); ?>/img/admin/history.png"/>
            <a href="/admin/historyout" >History out</a>
        </td>
        <td>
            <img src="<?php echo $this->baseUrl(); ?>/img/admin/history.png"/>
            <a href="/admin/historyin" >History in</a>
        </td>
    </tr>
    <tr>
        <td>
            <img src="<?php echo $this->baseUrl(); ?>/img/admin/artifacts.png"/>
            <a href="/admin/artifact" >Artifact</a>
        </td>
        <td>
            <img src="<?php echo $this->baseUrl(); ?>/img/admin/artifacts.png"/>
            <a href="/admin/artifactsfactors" >Artifacts factors</a>
        </td>
        <td>
            <img src="<?php echo $this->baseUrl(); ?>/img/admin/artifacts.png"/>
            <a href="/admin/artifactinventoryposition" >Artifact inventory position</a>
        </td>
    </tr>
    <tr>
        <td>
            <img src="<?php echo $this->baseUrl(); ?>/img/admin/map.png"/>
            <a href="/admin/map" >Map</a>
        </td>
        <td>
            <img src="<?php echo $this->baseUrl(); ?>/img/admin/castles.png"/>
            <a href="/admin/mapplayers" >Map players</a>
        </td>
        <td>
            <img src="<?php echo $this->baseUrl(); ?>/img/admin/castles.png"/>
            <a href="/admin/mapunits" >Map units</a>
        </td>
        <td>
            <img src="<?php echo $this->baseUrl(); ?>/img/admin/castles.png"/>
            <a href="/admin/castle" >Map castles</a>
        </td>
        <td>
            <img src="<?php echo $this->baseUrl(); ?>/img/admin/castles.png"/>
            <a href="/admin/mapcastlesproduction" >Map castles production</a>
        </td>
        <td>
            <img src="<?php echo $this->baseUrl(); ?>/img/admin/castles.png"/>
            <a href="/admin/mapruins" >Map ruins</a>
        </td>
        <td>
            <img src="<?php echo $this->baseUrl(); ?>/img/admin/castles.png"/>
            <a href="/admin/maptowers" >Map towers</a>
        </td>
        <td>
            <img src="<?php echo $this->baseUrl(); ?>/img/admin/castles.png"/>
            <a href="/admin/mapterrain" >Map terrain</a>
        </td>

    </tr>
</table>