<table id="main" cellspacing="20px">
    <tr>
        <td>
            <img src="<?php echo $this->baseUrl(); ?>/img/admin/administratorzy.png"/>
            <a href="/admin/player" >Player</a>
        </td>
        <td>
            <img src="<?php echo $this->baseUrl(); ?>/img/admin/artifacts.png"/>
            <a href="/admin/artifact" >Artifact</a>
        </td>
        <td>
            <img src="<?php echo $this->baseUrl(); ?>/img/admin/history.png"/>
            <a href="/admin/historyout" >History Out</a>
        </td>
        <td>
            <img src="<?php echo $this->baseUrl(); ?>/img/admin/history.png"/>
            <a href="/admin/historyin" >History In</a>
        </td>
    </tr>
    <tr>
        <td>
            <img src="<?php echo $this->baseUrl(); ?>/img/admin/map.png"/>
            <a href="/admin/map" >Map</a>
        </td>
        <td>
            <img src="<?php echo $this->baseUrl(); ?>/img/admin/castles.png"/>
            <a href="/admin/mapplayers" >Map Players</a>
        </td>
        <td>
            <img src="<?php echo $this->baseUrl(); ?>/img/admin/castles.png"/>
            <a href="/admin/castle" >Map Castles</a>
        </td>
        <td>
            <img src="<?php echo $this->baseUrl(); ?>/img/admin/castles.png"/>
            <a href="/admin/mapcastlesproduction" >Map castles production</a>
        </td>

    </tr>
</table>