<ul>
<li>
<a href="<?php echo $this->url(array('controller'=>'gamesetup')) ?>" class="button">New game</a>
</li>
<li>
<a href="<?php echo $this->url(array('controller'=>'gameload')) ?>" class="button">Load game</a>
</li>
<li>
<a href="<?php echo $this->url(array('controller'=>'hero')) ?>" class="button">Hero</a>
</li>
<li>
<a href="<?php echo $this->url(array('controller'=>'market')) ?>" class="button">Market</a>
</li>
</ul>
<script type="text/javascript">
if( jws.browserSupportsWebSockets() ) {
    lWSC = new jws.jWebSocketJSONClient();
    login();
}else{
    alert(jws.MSG_WS_NOT_SUPPORTED);
}
</script>
