<ul>
<li>
<a href="<?php echo $this->url(array('controller'=>'gamesetup')) ?>" class="button">New game</a>
</li>
<li>
<a href="<?php echo $this->url(array('controller'=>'gameload')) ?>" class="button">Load game</a>
</li>
<li>
<a href="<?php echo $this->url(array('controller'=>'hero')) ?>" class="button">Hero</a>
</li>
<li>
<a href="<?php echo $this->url(array('controller'=>'market')) ?>" class="button">Market</a>
</li>
</ul>
