<ul>
<li>
<a href="<?php echo $this->url(array('controller'=>'new')) ?>" class="button">New game</a>
</li>
<li>
<a href="<?php echo $this->url(array('controller'=>'load')) ?>" class="button">Load game</a>
</li>
<li>
<a href="<?php echo $this->url(array('controller'=>'hero')) ?>" class="button">Hero</a>
</li>
<li>
<a href="<?php echo $this->url(array('controller'=>'market')) ?>" class="button">Market</a>
</li>
</ul>
<script type="text/javascript">
if( jws.browserSupportsWebSockets() ) {
    lWSC = new jws.jWebSocketJSONClient();
    login();
}else{
    top.location = '<?php echo $this->url(array('controller'=>'index', 'action'=>'unsupported')) ?>';
}
</script>
