<h1><?php echo $this->translate('Play') ?></h1>
<h2><?php echo $this->translate('Create new game') ?>:</h2>
<table id="new">
    <tr>
        <td id="form">
            <?php echo $this->form; ?>
        </td>
        <td id="img">
            <img id="map"/>
        </td>
    </tr>
</table>

<h2><?php echo $this->translate('Join one of the games listed below') ?>:</h2>
<div class="table">
    <table></table>
    <p id="info"></p>
</div>
<br/>
<ul>
    <li>
        <a class="button" href="/">&laquo; <?php echo $this->translate('Back') ?></a>
    </li>
    <li>
        <a class="button" href="javascript:refresh()"><?php echo $this->translate('Refresh') ?></a>
    </li>
</ul>
<?php $this->headScript()->captureStart() ?>
var th = '<th><?php echo $this->translate('Map name') ?></th><th><?php echo $this->translate('Game master') ?></th><th><?php echo $this->translate('Current number of players') ?></th><th><?php echo $this->translate('Max number of players') ?></th><th><?php echo $this->translate('Date') ?></th>';
var lang = '<?php echo Zend_Registry::get('lang') ?>';
var info = '<?php echo $this->translate('There are no open games') ?>';
<?php $this->headScript()->captureEnd() ?>