<h2>Open games:</h2>
<div id="mygames"><table></table></div>
<ul>
    <li>
        <a class="button" href="<?php echo $this->url(array('controller' => 'index', 'gameId' => null)) ?>">< Back</a>
    </li>
    <li>
        <a class="button" href="<?php echo $this->url(array('controller' => 'new', 'action' => 'create')) ?>">Create</a>
    </li>
    <li>
        <a class="button" href="javascript:refresh()">Refresh</a>
    </li>
</ul>
<script type="text/javascript">
    var th = '<th>Game master</th><th>Current number of players</th><th>Max number of players</th><th>Date</th>';
    var url = '<?php echo $this->url(array('controller' => 'gamesetup', 'gameId' => null)) ?>';
    var mygames = $('#mygames table');
    function refresh() {
        $.getJSON("<?php echo $this->url(array('controller' => 'newajax', 'action' => 'refresh')) ?>", function(result) {

            mygames.html('');
            mygames.append(th);
            for(i in result) {
                mygames.append(
                $('<tr>')
                .addClass('gid'+result[i].gameId)
                .append($('<td>').append($('<a>').html(result[i].gameMaster)))
                .append($('<td>').append($('<a>').html(result[i].playersingame)))
                .append($('<td>').append($('<a>').html(result[i].numberOfPlayers)))
                .append($('<td>').append($('<a>').html(result[i].begin.split('.')[0])))
                .bind('click', { gameId: result[i].gameId }, makeUrl)
                .mouseover(function(){$(this).css('background','transparent url(../img/nav_bg.png) repeat')})
                .mouseleave(function(){$(this).css('background','transparent')})
            );
                $('#mygames td').mouseover(function(){
                    $('#mygames td').css('cursor', 'pointer')
                });
            }
        });
    }
    function makeUrl(event){
        top.location = url + '/index/gameId/' + event.data.gameId;
    }
    refresh();
    setInterval ( 'refresh()', 5000 );
</script>

