<h2><?php echo $this->translate('Select which game you want to load') ?></h2>
<div class="table">
    <table>
        <th><?php echo $this->translate('Game master') ?></th>
        <th><?php echo $this->translate('Your color') ?></th>
        <th><?php echo $this->translate('Turn number') ?></th>
        <th><?php echo $this->translate('Number of Players') ?></th>
        <th><?php echo $this->translate('Players') ?></th>
        <th><?php echo $this->translate('Start date') ?></th>
        <?php
        if (count($this->myGames)) {
            foreach ($this->myGames as $game) {
                $url = '/' . Zend_Registry::get('lang') . '/load/load/gameId/' . $game['gameId'];
                $gameMaster = $game['players'][$game['gameMasterId']]['firstName'] . ' ' . $game['players'][$game['gameMasterId']]['lastName'];
                echo '
    <tr id="gid' . $game['gameId'] . '" onclick="window.location.href = \'' . $url . '\';" class="trlink">
        <td><a href="' . $url . '">' . $gameMaster . '</a></td>
        <td class="' . $game['color'] . 'bg"><a href="' . $url . '">' . $game['color'] . '</a></td>
        <td><a href="' . $url . '">' . $game['turnNumber'] . '</a></td>
        <td><a href="' . $url . '">' . $game['numberOfPlayers'] . '</a></td>
        <td><a href="' . $url . '">';
                foreach ($game['players'] as $v) {
                    echo '<span class="font-' . $v['color'] . '">' . $v['firstName'] . ' ' . $v['lastName'] . ' /' . $v['color'] . '/</span><br/>';
                }
                echo '</a></td>
        <td><a href="' . $url . '">' . strftime('%F %H:%M:%S', strtotime($game['begin'])) . '</a></td>
    </tr>
    ';
            }
        }
        ?>
    </table>
</div>
<?php echo $this->paginationControl($this->myGames, 'Sliding', 'pagination_control.phtml'); ?>
<ul>
    <li>
        <a href="/" class="button">&laquo; <?php echo $this->translate('Back') ?></a>
    </li>
</ul>
<script type="text/javascript">
    $('.trlink')
            .mouseover(function () {
                $('#' + this.id).css('background', 'transparent url(../img/nav_bg.png) repeat');
            })
            .mouseleave(function () {
                $('#' + this.id).css('background', 'transparent');
            });
</script>