<h1>Waiting for other players...</h1>

<p>Number of players: "<?php echo $this->game['numberOfPlayers'] ?>"</p>
<p>Game: "<?php echo $this->game['gameId'] ?>"</p>
<p>Game started: "<?php echo substr($this->game['begin'], 0, strpos($this->game['begin'], '.')) ?>"</p>

<h2>Players:</h2>
<table id="playersingame">
    <?php
    for ($i = 0; $i < $this->game['numberOfPlayers']; $i++) {
        echo '<tr id="' . $this->colors[$i] . '"><td id="' . $this->colors[$i] . 'Id"><div class="left">empty</div><div class="right">' . $this->colors[$i] . '</div></td></tr>';
    }
    ?>
</table>

<ul>
    <li><a href="<?php echo $this->url(array('controller' => 'load', 'action' => 'index', 'gameId' => null)) ?>" class="button">< Back</a></li>
    <li><a href="javascript:refresh()" class="button">Refresh</a></li>
</ul>
<?php
$script = '
    var urlRedirect = "/game/index";
    var urlRefresh = "/loadajax/refresh";
    var urlUpdate = "/loadajax/update";
    var alivePlayers = ' . Zend_Json::encode($this->game['alive']) . ';
    var ready = 0;
    var playerId = ' . (int) $this->player['playerId'] . ';
    var color = "' . $this->player['color'] . '";
    var channel = "ch' . $this->game['gameId'] . '";
    var lAccessKey = "' . $this->game['lAccessKey'] . '";
    var lSecretKey = "' . $this->game['lSecretKey'] . '";
';

$this->headScript()->appendScript($script);
