<?php
if (isset($this->heroes[0])) {
    echo 'Attack points: ' . $this->heroes[0]['attackPoints'] . '</br>';
    echo 'Defense points: ' . $this->heroes[0]['defensePoints'] . '</br>';
    echo 'Number of moves: ' . $this->heroes[0]['numberOfMoves'] . '</br>';
}


echo $this->form

?>
<h2><?php echo $this->translate('Artifacts') ?>:</h2>
<div class="table">
    <table>
        <th><?php echo $this->translate('Name') ?></th>
        <th><?php echo $this->translate('Quantity') ?></th>
        <?php
        if (count($this->chest)) {
            foreach ($this->chest as $artifact) {
                echo '<tr><td>' . $this->artifacts[$artifact['artifactId']]['name'] . '</td><td>' . $artifact['quantity'] . '</td></tr>';
            }
        }
        ?>
    </table>

</div>
<ul>
    <li>
        <a class="button" href="/">&laquo; Back</a>
    </li>
</ul>