<div>
    <ul>
        <li>
            <a href="<?php echo $this->url(array('controller'=>'gamesetup')) ?>" class="button">New game</a>
        </li>
        <li>
            <a href="<?php echo $this->url(array('controller'=>'gameload')) ?>" class="button">Load game</a>
        </li>
        <li>
            <a href="<?php echo $this->url(array('controller'=>'hero')) ?>" class="button">Hero</a>
        </li>
        <li>
            <a href="<?php echo $this->url(array('controller'=>'market')) ?>" class="button">Market</a>
        </li>
    </ul>
</div>
<?php
if(isset($this->heroes[0])){
    echo 'Attack points: '.$this->heroes[0]['attackPoints'].'</br>';
    echo 'Defense points: '.$this->heroes[0]['defensePoints'].'</br>';
    echo 'Number of moves: '.$this->heroes[0]['numberOfMoves'].'</br>';
}


echo $this->form

?>