
<?php
if(isset($this->heroes[0])){
    echo 'Attack points: '.$this->heroes[0]['attackPoints'].'</br>';
    echo 'Defense points: '.$this->heroes[0]['defensePoints'].'</br>';
    echo 'Number of moves: '.$this->heroes[0]['numberOfMoves'].'</br>';
}


echo $this->form

?>
<ul>
    <li>
        <a class="button" href="<?php echo $this->url(array('controller' => 'index', 'gameId' => null)) ?>">< Back</a>
    </li>
</ul>