<?php
            if ($this->turn['playerId'] == $this->playerId) {
                $myTurn = 'true';
            } else {
                $myTurn = 'false';
            }
?>
<script type="text/javascript">
    <?php $this->headScript()->captureStart() ?>
    //var colors = <?php echo Zend_Json::encode($this->colors); ?>;
    var fields = <?php echo Zend_Json::encode($this->fields); ?>;
    var ruins = <?php echo Zend_Json::encode($this->ruins); ?>;
    Image1= new Image(27,32);
    Image1.src = '../img/game/cursor_attack.png';
    Image2= new Image(14,46);
    Image2.src = '../img/game/cursor_castle.png';
    Image3= new Image(25,26);
    Image3.src = '../img/game/cursor_select.png';
    Image4= new Image(20,20);
    Image4.src = '../img/game/footsteps_e.png';
    Image5= new Image(20,20);
    Image5.src = '../img/game/footsteps_n.png';
    Image6= new Image(20,20);
    Image6.src = '../img/game/footsteps_s.png';
    Image7= new Image(20,20);
    Image7.src = '../img/game/footsteps_w.png';
    Image8= new Image(20,20);
    Image8.src = '../img/game/footsteps_ne.png';
    Image9= new Image(20,20);
    Image9.src = '../img/game/footsteps_nw.png';
    Image10= new Image(20,20);
    Image10.src = '../img/game/footsteps_se.png';
    Image11= new Image(20,20);
    Image11.src = '../img/game/footsteps_sw.png';
    var players = <?php echo Zend_Json::encode($this->players); ?>;
    var castles = <?php echo Zend_Json::encode($this->castlesSchema); ?>;
    my.color = '<?php echo $this->color ?>';
    my.turn = <?php echo $myTurn ?>;
    turn.color = '<?php echo $this->turn['color'] ?>';
    turn.nr = '<?php echo $this->turn['nr'] ?>';
    var urlMove = '<?php echo $this->url(array('controller' => 'move', 'action' => 'go', 'armyId' => null, 'x' => null, 'y' => null)) ?>';
    var urlNextTurn = '<?php echo $this->url(array('controller' => 'turn', 'action' => 'next')) ?>';
    var urlStartMyTurn = '<?php echo $this->url(array('controller' => 'turn', 'action' => 'start')) ?>';
    var urlFightCastle = '<?php echo $this->url(array('controller' => 'fight', 'action' => 'castle')) ?>';
    var urlFightArmy = '<?php echo $this->url(array('controller' => 'fight', 'action' => 'army')) ?>';
    var urlAddArmy = '<?php echo $this->url(array('controller' => 'gameajax', 'action' => 'addarmy')) ?>';
    var urlGetPlayerArmies = '<?php echo $this->url(array('controller' => 'gameajax', 'action' => 'armies')) ?>';
    var urlSplitArmy = '<?php echo $this->url(array('controller' => 'gameajax', 'action' => 'split')) ?>';
    var urlDisbandArmy = '<?php echo $this->url(array('controller' => 'gameajax', 'action' => 'disband')) ?>';
    var urlSearchRuins = '<?php echo $this->url(array('controller' => 'gameajax', 'action' => 'ruins')) ?>';
    var urlSetProduction = '<?php echo $this->url(array('controller' => 'production', 'action' => 'set')) ?>';
    var urlCastleRaze = '<?php echo $this->url(array('controller' => 'castle', 'action' => 'raze')) ?>';
    var urlCastleBuild = '<?php echo $this->url(array('controller' => 'castle', 'action' => 'build')) ?>';
    var urlCastleGet = '<?php echo $this->url(array('controller' => 'castle', 'action' => 'get')) ?>';
    <?php $this->headScript()->captureEnd() ?>
    var board = $("#board")
    .mousedown(function(event) {
        if(lock) {
            return null;
        }

        switch (event.which) {
            case 1:
                if(selectedArmy != null) {
                    sendMove(cursorPosition(event.pageX, event.pageY));
                }
                break;
            case 2:
                alert('Middle mouse button pressed');
                break;
            case 3:
                unselectArmy();
                break;
            default:
                alert('You have a strange mouse');
        }
    })
    .mousemove(function(e) {
        if(lock) {
            return null;
        }
        cursorPosition(e.pageX, e.pageY);
    });

    $('#'+my.color+'Color').append('You');
    $('#'+turn.color+'Turn').html('Turn ' + turn.nr);
    $('#connect').click(function(){login()});
    $('#nextTurn').click(function(){sendNextTurn()});
    $('#nextArmy').click(function(){findNextArmy()});
    $('#splitArmy').click(function(){splitArmyM()});
    $('#disbandArmy').click(function(){disbandArmyM()});
    goldUpdate(<?php echo $this->gold ?>);

</script>
