<?php $this->headScript()->captureStart() ?>
var fields = <?php echo Zend_Json::encode($this->fields); ?>;
var ruins = <?php echo Zend_Json::encode($this->ruins); ?>;
var units = <?php echo Zend_Json::encode($this->units); ?>;
var towers = <?php echo Zend_Json::encode($this->towers); ?>;
var artefacts = <?php echo Zend_Json::encode($this->artefacts); ?>;
var players = <?php echo Zend_Json::encode($this->players); ?>;
var castles = <?php echo Zend_Json::encode($this->castlesSchema); ?>;
var my = new Array();
my.color = '<?php echo $this->color ?>';
my.turn = <?php echo $this->myTurn ?>;
my.game = <?php echo $this->myGame ?>;
var turn = new Array();
turn.color = '<?php echo $this->turn['color'] ?>';
turn.nr = '<?php echo $this->turn['nr'] ?>';
var channel = 'ch<?php echo $this->game['gameId'] ?>';
var lAccessKey = '<?php echo $this->game['lAccessKey'] ?>';
var lSecretKey = '<?php echo $this->game['lSecretKey'] ?>';
$(document).ready(function() {
    goldUpdate(<?php echo $this->gold ?>);
});
<?php $this->headScript()->captureEnd() ?>
