<?php
            if ($this->turn['playerId'] == $this->playerId) {
                $myTurn = 'true';
            } else {
                $myTurn = 'false';
            }
?>
<script type="text/javascript">
    goldUpdate(<?php echo $this->gold ?>);
    var colors = <?php echo Zend_Json::encode($this->colors); ?>;
    <?php $this->headScript()->captureStart() ?>
    var fields = <?php echo Zend_Json::encode($this->fields); ?>;
    <?php $this->headScript()->captureEnd() ?>

    var players = <?php echo Zend_Json::encode($this->players); ?>;
    var castles = <?php echo Zend_Json::encode($this->castlesSchema); ?>;
    my.color = '<?php echo $this->color ?>';
    my.playerId = '<?php echo $this->playerId ?>';
    turn.color = '<?php echo $this->turn['color'] ?>';
    turn.playerId = '<?php echo $this->turn['playerId'] ?>';
    turn.myTurn = <?php echo $myTurn ?>;
    var urlMove = '<?php echo $this->url(array('controller' => 'move', 'action' => 'go', 'armyId' => null, 'x' => null, 'y' => null)) ?>';
    var urlNextTurn = '<?php echo $this->url(array('controller' => 'turn', 'action' => 'next')) ?>';
    var urlStartMyTurn = '<?php echo $this->url(array('controller' => 'turn', 'action' => 'start')) ?>';
    var urlFightCastle = '<?php echo $this->url(array('controller' => 'fight', 'action' => 'castle')) ?>';
    var urlFightArmy = '<?php echo $this->url(array('controller' => 'fight', 'action' => 'army')) ?>';
    var urlAddArmy = '<?php echo $this->url(array('controller' => 'gameajax', 'action' => 'addarmy')) ?>';
    var urlGetPlayerArmies = '<?php echo $this->url(array('controller' => 'gameajax', 'action' => 'armies')) ?>';
    var urlSplitArmy = '<?php echo $this->url(array('controller' => 'gameajax', 'action' => 'split')) ?>';
    var urlSetProduction = '<?php echo $this->url(array('controller' => 'production', 'action' => 'set')) ?>';
    var urlCastleRaze = '<?php echo $this->url(array('controller' => 'castle', 'action' => 'raze')) ?>';
    var urlCastleBuild = '<?php echo $this->url(array('controller' => 'castle', 'action' => 'build')) ?>';
    var urlCastleGet = '<?php echo $this->url(array('controller' => 'castle', 'action' => 'get')) ?>';
    var board = $("#board")
    .mousedown(function(event) {
        if(lock) {
            return null;
        }

        switch (event.which) {
            case 1:
                if(selectedArmy != null) {
                    sendMove(cursorPosition(event.pageX, event.pageY));
                }
                break;
            case 2:
                alert('Middle mouse button pressed');
                break;
            case 3:
                unselectArmy();
                break;
            default:
                alert('You have a strange mouse');
        }
    })
    .mousemove(function(e) {
        if(lock) {
            return null;
        }
        cursorPosition(e.pageX, e.pageY);
    });

    $('#'+my.color+'Color').append('You');
    $('#'+turn.color+'Turn').html('Turn');
    $('#connect').click(function() {
        login();
//         wsConnect();
    });
    $('#nextTurn').click(function(){sendNextTurn()});
    $('#nextArmy').click(function(){findNextArmy()});

//     var enemyArmies = new Array();
//     enemyArmies[0] = jQuery.parseJSON('{"0":{"defensePoints":3,"soldierId":"s1"},"1":{"defensePoints":3,"soldierId":"s2"},"2":{"defensePoints":3,"soldierId":"s3"}}');
//     enemyArmies[0] = jQuery.parseJSON('{"color":"neutral","heroes":[],"soldiers":[{"soldierId":"s1","name":"light infantry"},{"soldierId":"s2","name":"light infantry"},{"soldierId":"s3","name":"light infantry"}]}');
//     console.log(enemyArmies);
</script>
