<div class="paginationControl">
    <?php if ($this->pageCount): ?>
    <div>
        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?><a
            href="<?php echo $this->url(array('page' => $this->previous)); ?>"><?php echo $this->translate('Previous'); ?></a><?php else: ?><?php echo $this->translate('Previous'); ?><?php endif; ?>
        <!-- Next page link -->
        <?php if (isset($this->next)): ?><a
            href="<?php echo $this->url(array('page' => $this->next)); ?>"><?php echo $this->translate('Next'); ?></a><?php else: ?><?php echo $this->translate('Next'); ?><?php endif; ?>
    </div>
    <?php endif; ?>
    <div class="box_pagination">
        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
        <?php if ($page != $this->current): ?><a
                href="<?php echo $this->url(array('page' => $page)); ?>">{<?php echo $page; ?>}</a><?php else: ?>
            {<?php echo $page; ?>}<?php endif; ?>
        <?php endforeach; ?>
    </div>
</div>

