<div class="paginationControl">
    <?php if ($this->pageCount > 1): ?>
        <div>
            <div class="left">
                <?php if (isset($this->previous)): ?>
                    <a class="button" href="<?php echo $this->url(array('page' => $this->previous)); ?>"><?php echo $this->translate('Previous'); ?></a>
                <?php else: ?>
                    <span class="button buttonOff"><?php echo $this->translate('Previous'); ?></span>
                <?php endif; ?>
            </div>
            <div class="right">
                <?php if (isset($this->next)): ?>
                    <a class="button" href="<?php echo $this->url(array('page' => $this->next)); ?>"><?php echo $this->translate('Next'); ?></a>
                <?php else: ?>
                    <span class="button buttonOff"><?php echo $this->translate('Next'); ?></span>
                <?php endif; ?>

            </div>
        </div>
        <div class="box_pagination">
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <a class="button" href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a>
                <?php else: ?>
                    <span class="button buttonOff"><?php echo $page; ?></span>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
</div>

