<h1><?php echo $this->translate('Help') ?></h1>
<h2><?php echo $this->translate('') ?></h2>
<div class="table">
    <?php if (count($this->list)): ?>
        <?php foreach ($this->list as $row): ?>
            <div style="border: 1px solid #c0c0c0;border-radius:5px;padding: 10px">
                <div style="position: relative;width: 738px;height: 150px">
                    <div style="border-radius:5px;width: 60px;background: #000">
                        <img style="margin: 10px;padding: 10px;border: none"
                             src="/img/game/units/white/<?php echo str_replace(' ', '_', strtolower($row['name'])) ?>.png"/>
                    </div>

                    <h3 style="position: absolute;top: 10px;left:73px"><?php if (isset($row['name_lang']) && $row['name_lang']): echo $row['name_lang'];
                        else: echo $row['name']; endif ?></h3>

                    <div style="position: absolute;top: 40px;left:73px"><?php echo $this->translate('Cost') ?>: <span
                            class="yellow"><?php echo $row['cost'] ?></span></div>

                    <?php if ($row['special']): ?>
                        <div
                            style="position: absolute;top: 10px;left:370px"><?php echo $this->translate('Special unit') ?></div>
                    <?php endif ?>

                    <div style="position: absolute;top: 80px;left:20px">
                        <div><?php echo $this->translate('Attack') ?>: <span
                                class="yellow"><?php echo $row['attackPoints'] ?></span></div>
                        <div><?php echo $this->translate('Defense') ?>: <span
                                class="yellow"><?php echo $row['defensePoints'] ?></span></div>
                        <div><?php echo $this->translate('Moves') ?>: <span
                                class="yellow"><?php echo $row['numberOfMoves'] ?></span></div>
                    </div>
                    <div style="position: absolute;top: 80px;left:160px">
                        <div><?php echo $this->translate('Can fly') ?>: <span class="yellow">
                            <?php if ($row['canFly']): ?>
                                <?php echo $this->translate('Yes') ?>
                            <?php else: ?>
                                <?php echo $this->translate('No') ?>
                            <?php endif ?></span>
                        </div>
                        <div><?php echo $this->translate('Can swim') ?>: <span class="yellow">
                            <?php if ($row['canSwim']): ?>
                                <?php echo $this->translate('Yes') ?>
                            <?php else: ?>
                                <?php echo $this->translate('No') ?>
                            <?php endif ?></span>
                        </div>
                    </div>
                    <div style="position: absolute;top: 80px;left:330px">
                        <div><?php echo $this->translate('Movement cost through the forest') ?>: <span
                                class="yellow"><?php echo $row['modMovesForest'] ?></span></div>
                        <div><?php echo $this->translate('Movement cost through the swamp') ?>: <span
                                class="yellow"><?php echo $row['modMovesSwamp'] ?></span></div>
                        <div><?php echo $this->translate('Movement cost through the hills') ?>: <span
                                class="yellow"><?php echo $row['modMovesHills'] ?></span></div>
                    </div>
                </div>
            </div>
            <br/>
        <?php endforeach ?>
    <?php endif ?>
</div>
<br/>
<div id="pagination"></div>
<ul>
    <li>
        <a href="/" class="button">&laquo; <?php echo $this->translate('Back') ?></a>
    </li>
</ul>