<h1><?php echo $this->translate('New game') ?></h1>
<p><?php echo $this->translate('Map') ?>: <?php echo $this->map ?></p>
<p><?php echo $this->translate('Required number of players') ?>: <?php echo $this->numberOfPlayers ?></p>
<p><?php echo $this->translate('Time limit') ?>: <?php echo $this->timeLimit ?></p>
<p><?php echo $this->translate('Limit of the number of turns') ?>: <?php echo $this->turnsLimit ?></p>
<p><?php echo $this->translate('Time limit per turn') ?>: <?php echo $this->turnTimeLimit ?></p>
<h2><?php echo $this->translate('Select your color and team') ?></h2>
<table id="playersingame">
    <th><?php echo $this->translate('Player name & color') ?></th>
    <th><?php echo $this->translate('Select your color') ?></th>
    <th><?php echo $this->translate('Human/AI') ?></th>
    <?php for ($i = 0; $i < $this->numberOfPlayers; $i++): ?>
        <tr id="<?php echo $this->mapPlayers[$i]['mapPlayerId'] ?>">
            <td class="td1">
                <div class="left"></div>
                <div class="right"
                     style="background: <?php echo $this->mapPlayers[$i]['backgroundColor'] ?>;color: <?php echo $this->mapPlayers[$i]['textColor'] ?>"><?php echo $this->mapPlayers[$i]['longName'] ?></div>
            </td>
            <td class="td2"></td>
            <td class="td3"></td>
        </tr>
    <?php endfor; ?>
</table>

<ul style="float: right">
    <li id="start"></li>
</ul>

<ul>
    <li><a class="button"
           href="/<?php echo Zend_Registry::get('lang') ?>/new">&laquo; <?php echo $this->translate('Back') ?></a></li>
</ul>

<?php $this->headScript()->captureStart() ?>
var numberOfPlayers = <?php echo (int)$this->numberOfPlayers ?>;
var mapPlayers = <?php echo Zend_Json::encode($this->mapPlayers) ?>;

var gameId = <?php echo (int)$this->gameId ?>;
var playerId = <?php echo (int)$this->player['playerId'] ?>;
var accessKey = '<?php echo $this->accessKey ?>';

var urlGemesetupStart = '/<?php echo Zend_Registry::get('lang') ?>/setup/start';
var select = '<?php echo $this->translate('Select') ?>';
var deselect = '<?php echo $this->translate('Deselect') ?>';
var kick = '<?php echo $this->translate('Kick') ?>';
var human = '<?php echo $this->translate('Human') ?>';
var computer = '<?php echo $this->translate('computer') ?>';
<?php $this->headScript()->captureEnd() ?>