<h1><?php echo $this->translate('New game') ?></h1>
<h2><?php echo $this->translate('Waiting for other players') ?></h2>

<script type="text/javascript">
    function refresh() {
        $.getJSON('/en/setupajax/allarmiesready', function (result) {
            if (result.all) {
                top.location.assign('/<?php echo  Zend_Registry::get('lang') ?>/game');
            }
        });
    }
    $(document).ready(function () {
        setInterval('refresh()', 5000);
    });

</script>
