<?php echo $this->doctype() . "\n" ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pl" lang="pl">
    <head>
        <?php
        echo $this->headMeta() . "\n";
        echo $this->headTitle() . "\n";
        echo $this->headLink() . "\n";
        echo $this->headScript() . "\n";
        ?>
    </head>
    <body>
        <div id="header">
            <div id="mainmenu">
                <h1>PANEL ADMINISTRACYJNY</h1>
                <?php echo $this->placeholder('mainmenu') ?>
            </div>
        </div>
        <div id="page">
            <div id="center">
                <?php echo $this->placeholder('pagetitle') ?>
                <?php echo $this->layout()->content ?>
            </div>
            <div id="footer"><?php echo $this->placeholder('copyright') ?></div>
        </div>
    </body>
</html>