<?php echo $this->doctype() . "\n" ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pl" lang="pl">
    <head>
        <?php
        echo $this->headMeta() . "\n";
        echo $this->headTitle() . "\n";
        echo $this->headLink() . "\n";
        echo $this->headScript() . "\n";
        ?>
    </head>
    <body>
        <div id="header"><h1>PANEL ADMINISTRACYJNY</h1></div>
        <div id="page">
            <img id="lock" src="/img/admin/lock.png" />
            <h3>Core-T Content Managment System</h3>
            <div id="center">
                <?php echo $this->layout()->content ?>
            </div>
        </div>
        <div id="page2">
            <div id="center2">
                Wpisz swój Identyfikator i Hasło. Pamiętaj, że dla systemu ma znaczenie, czy wpisujesz małe, czy też wielkie litery (sprawdź, czy nie masz włączonej funkcji Caps Lock na klawiaturze).
            </div>
        </div>
        <div id="footer"><?php echo $this->placeholder('copyright') ?></div>
    </body>
</html>