<?php echo $this->doctype() ?>
<html>
<head>
    <?php
    echo $this->headMeta() . "\n";
    echo $this->headTitle() . "\n";
    echo $this->headLink() . "\n";
    echo $this->headScript() . "\n";
    ?>
</head>
<body onkeydown="Gui.doKey(arguments[0] || window.event)">
<div id="page">
    <div id="menuTop">
        <?php echo $this->placeholder('version') ?>
        <?php echo $this->placeholder('logout') ?>
        <a href="/<?php echo Zend_Registry::get('lang') ?>/index"
           class="button"><?php echo $this->translate('Quit game') ?></a>
    </div>
    <div id="game">
        <!-- ZOOM WINDOW -->
        <div class="zoomWindow">
            <div class="zoomPadLayout">
                <div class="zoomPad">
                    <div class="zoomPup"></div>
                    <?php echo $this->placeholder('map') ?>
                </div>
            </div>
            <div id="terrain"> <?php echo $this->translate('Terrain') ?>: <span id="coord" class="font-yellow"></span>
            </div>
            <div class="message"></div>
            <div id="goldBox" class="box">
                <div class="left">
                    <div><?php echo $this->translate('Income') ?></div>
                    <div class="text-right font-yellow" id="income">0</div>
                </div>
                <div class="left">
                    <div><?php echo $this->translate('Upkeep') ?></div>
                    <div class="text-right font-yellow" id="costs">0</div>
                </div>
                <div class="left">
                    <div><?php echo $this->translate('Treasure') ?></div>
                    <div class="text-right font-yellow" id="gold">0</div>
                </div>
            </div>
            <div id="playersBox" class="box">
                <!--                <img id="aaawhite" src="/img/game/heroes/white.png">-->
                <div id="turn"><span id="turnNumber"></span></div>
                <canvas id="playersCanvas" width="180px" height="180px"></canvas>
                <div id="turnBox">
                    <div id="surrender" title="<?php echo $this->translate('Surrender') ?>"></div>
                    <div>
                        <a id="nextTurn" class="button"><?php echo $this->translate('Next turn') ?> &raquo;</a>
                    </div>
                </div>
                <div id="close">X</div>
            </div>
            <div id="armyBox" class="box">
                <div id="nameBox"><?php echo $this->translate('Name') ?>: <span id="name" class="font-yellow"></span>
                </div>
                <div id="attrBox">
                    <div class="left"><?php echo $this->translate('Moves') ?>: <span id="moves"
                                                                                     class="font-yellow"></span></div>
                    <div class="left"><?php echo $this->translate('Attack') ?>: <span id="attack"
                                                                                      class="font-yellow"></span></div>
                    <div class="left"><?php echo $this->translate('Defense') ?>: <span id="defense"
                                                                                       class="font-yellow"></span></div>
                </div>
                <div id="armyButtonsBox">
                    <div class="armyButtons">
                        <div class="left armyButton">
                            <a id="disbandArmy"
                               class="button buttonOff"><?php echo $this->translate('Disband army') ?></a>
                        </div>
                        <div class="left armyButton">
                            <a id="unselectArmy"
                               class="button buttonOff"><?php echo $this->translate('Unselect army') ?></a>
                        </div>
                        <div class="left armyButton">
                            <a id="searchRuins"
                               class="button buttonOff"><?php echo $this->translate('Search ruins') ?></a>
                        </div>
                        <!--                        <div class="left armyButton">-->
                        <!--                            <a id="showArtifacts"-->
                        <!--                               class="button buttonOff">-->
                        <?php //echo $this->translate('Show artifacts') ?><!--</a>-->
                        <!--                        </div>-->
                        <div class="left armyButton">
                            <a id="splitArmy" class="button buttonOff"><?php echo $this->translate('Split army') ?></a>
                        </div>
                        <div class="left armyButton">
                            <a id="armyStatus"
                               class="button buttonOff"><?php echo $this->translate('Army status') ?></a>
                        </div>
                        <div class="left armyButton">
                            <a id="quitArmy" class="button buttonOff"><?php echo $this->translate('Fortify army') ?></a>
                        </div>
                        <div class="left armyButton">
                            <a id="skipArmy"
                               class="button buttonOff"><?php echo $this->translate('Skip in this turn') ?></a>
                        </div>
                        <div class="left armyButton">
                            <a id="nextArmy"
                               class="button buttonOff">(n) <?php echo $this->translate('Find next army') ?> &raquo;</a>
                        </div>
                    </div>
                </div>
                <div id="close">X</div>
            </div>
            <div id="timerBox" class="box">
                <table>
                    <tr>
                        <th><?php echo $this->translate('Color') ?></th>
                        <th><?php echo $this->translate('Turn nr') ?></th>
                        <th><?php echo $this->translate('Time spend') ?></th>
                    </tr>
                </table>
            </div>
            <div id="chatBox" class="box">
                <div id="chatWindow">
                    <div></div>
                </div>
                <div class="send">
                    <div class="left"><input type="text" name="msg" id="msg"></div>
                    <div class="right"><a id="send" class="button"><?php echo $this->translate('Send') ?></a></div>
                </div>
                <div id="close">X</div>
            </div>
            <?php echo $this->placeholder('board') ?>
        </div>
    </div>
</div>
</body>
</html>
<?php echo $this->layout()->content; ?>
