<?php echo $this->doctype() ?>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <?php
        echo $this->headTitle() . "\n";
        echo $this->headLink() . "\n";
        echo $this->headScript() . "\n";
        echo $this->headMeta() . "\n";
        ?>
    </head>
    <body>
        <div id="page">
            <div id="menuTop"><a href="<?php echo $this->url(array('controller'=>'login', 'action'=>'logout')); ?>">Logout</a></div>
            <div id="game">
                <div class="zoomPad">
                    <div class="zoomPup"></div>
                    <img id="map" src="/img/game/board.png" width="202px">
                </div>
                <div id="gameMenu">
                    <div class="gameMenu">
                        <table id="colors">
                            <tr class="white"><td id="whiteColor"></td><td id="whiteTurn"></td></tr>
                            <tr class="green"><td id="greenColor"></td><td id="greenTurn"></td></tr>
                            <tr class="yellow"><td id="yellowColor"></td><td id="yellowTurn"></td></tr>
                            <tr class="red"><td id="redColor"></td><td id="redTurn"></td></tr>
                            <tr class="orange"><td id="orangeColor"></td><td id="orangeTurn"></td></tr>
                        </table>
                        <a id="nextTurn" class="button"></a>
                    </div>
                    <div class="gameMenu">
                        <p id="coord"></p>
                        <p id="info"></p>
                        <p id="name"></p>
                        <p id="moves"></p>
                        <a id="nextArmy" class="button"></a>
                    </div>
                    <div class="gameMenu">
                        <a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index')); ?>">Quit game</a>
                        <p id="wsStatus"></p>
                        <a id="connect" href="#">Connect</a>
                        <p id="log"></p>
                        <p id="income"></p>
                        <p id="costs"></p>
                        <p id="gold"></p>
                    </div>
                </div>
                <div class="zoomWindow">
                    <div id="board"></div>
                </div>
            </div>
        </div>
    </body>
</html>
<?php echo $this->layout()->content; ?>
