<?php echo $this->doctype() ?>
<html>
    <head>
        <?php
        echo $this->headMeta() . "\n";
        echo $this->headTitle() . "\n";
        echo $this->headLink() . "\n";
        echo $this->headScript() . "\n";
        ?>
    </head>
    <body>
        <div id="page">
            <div id="menuTop">
                <?php echo $this->placeholder('version') ?>
                <?php echo $this->placeholder('logout') ?>
                <a href="/index">Quit game</a>
            </div>
            <div id="game">
                <!-- ZOOM WINDOW -->
                <div class="zoomWindow">
                    <div class="zoomPadLayout">
                        <div class="zoomPad">
                            <div class="zoomPup"></div>
                            <img id="map" src="/img/game/board.png" width="218px">
                        </div>
                    </div>
                    <div id="terrain"> Terrain: <span id="coord" class="font-yellow"></span></div>
                    <div id="goldBox">
                        <div class="left">
                            <div>Income</div>
                            <div class="text-right font-yellow" id="income">0</div>
                        </div>
                        <div class="left">
                            <div>Costs</div>
                            <div class="text-right font-yellow" id="costs">0</div>
                        </div>
                        <div class="left">
                            <div>Treasure</div>
                            <div class="text-right font-yellow" id="gold">0</div>
                        </div>
                    </div>
                    <div id="playersBox">
                        <div id="turn"><span id="turnNumber"></span></div>
                        <div id="first" class="nr white">1</div>
                        <div id="second" class="nr yellow">2</div>
                        <div id="third" class="nr green">3</div>
                        <div id="fourth" class="nr red">4</div>
                        <div id="playersLabel">Players</div>
                        <div class="playersBox">
                            <div class="left white">
                                <div class="color">
                                    <div class="type"></div>
                                </div>
                            </div>
                            <div class="left yellow">
                                <div class="color">
                                    <div class="type"></div>
                                </div>
                            </div>
                        </div>
                        <div class="playersBox">
                            <div class="right green">
                                <div class="color">
                                    <div class="type"></div>
                                </div>
                            </div>
                            <div class="right red">
                                <div class="color">
                                    <div class="type"></div>
                                </div>
                            </div>
                        </div>
                        <div id="turnBox">
                            <div class="right"><a id="nextTurn" class="button">Next turn >></a></div>
                        </div>
                    </div>
                    <div id="armyBox">
                        <div id="nameBox">Name: <span id="name" class="font-yellow"></span></div>
                        <div id="attrBox">
                            <div class="left">Moves: <span id="moves" class="font-yellow"></span></div>
                            <div class="left">Attack: <span id="attack" class="font-yellow"></span></div>
                            <div class="left">Defense: <span id="defense" class="font-yellow"></span></div>
                        </div>
                        <div id="armyButtonsBox">
                            <div class="armyButtons">
                                <div class="left armyButton">
                                    <a id="disbandArmy" class="button buttonOff">Disband army</a>
                                </div>
                                <div class="left armyButton">
                                    <a id="splitArmy" class="button buttonOff">Split army</a>
                                </div>
                                <div class="left armyButton">
                                    <a id="armyStatus" class="button buttonOff">Army status</a>
                                </div>
                                <div class="left armyButton">
                                    <a id="searchRuins" class="button buttonOff">Search ruins</a>
                                </div>
                                <div class="left armyButton">
                                    <a id="quitArmy" class="button buttonOff">Fortify army</a>
                                </div>
                                <div class="left armyButton">
                                    <a id="skipArmy" class="button buttonOff">Skip in this turn</a>
                                </div>
                                <div class="left armyButton">
                                    <a id="unselectArmy" class="button buttonOff">Unselect army</a>
                                </div>
                                <div class="left armyButton">
                                    <a id="nextArmy" class="button buttonOff">Find next army >></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div id="board" style="background: url('../img/game/board.png') no-repeat;width: 4360px;height:2760px;"></div>
                    <div id="chatBox">
                        <div id="chatWindow"><div></div></div>
                        <div class="send">
                            <div class="left"><input type="text" name="msg" id="msg"></div>
                            <div class="right"><a id="send" class="button">Chat</a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>
<?php echo $this->layout()->content; ?>
