<?php echo $this->doctype() ?>
<html>
    <head>
        <?php
        echo $this->headMeta() . "\n";
        echo $this->headTitle() . "\n";
        echo $this->headLink() . "\n";
        echo $this->headScript() . "\n";
        ?>
    </head>
    <body>
        <div id="page">
            <div id="menuTop">
<!--                <p>Server status: <span id="wsStatus">WebSocket disconnected</span></p>-->
                <?php echo $this->placeholder('logout') ?>
            </div>
            <div id="content">
                <?php echo $this->placeholder('mainMenu') ?>
                <hr/>
                <?php echo $this->layout()->content ?>
            </div>
        </div>
    </body>
</html>