<?php echo $this->doctype() ?>
<html>
    <head>        
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">        
        <?php
        echo $this->headTitle() . "\n";
        echo $this->headLink() . "\n";
        echo $this->headScript() . "\n";
        echo $this->headMeta() . "\n";
        ?>
    </head>
    <body>
        <div id="page">
            <div id="menuTop">
                <p>Server status: <span id="wsStatus">WebSocket not supported!</span></p>
                <?php echo $this->placeholder('logout') ?>
            </div>
            <div id="content">
                <?php echo $this->placeholder('mainMenu') ?>
                <?php echo $this->placeholder('webSocket') ?>
                <?php echo $this->layout()->content ?>
            </div>
        </div>
    </body>
</html>