<?php echo $this->doctype() ?>
<html>
    <head>        
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">        
        <?php
        echo $this->headTitle() . "\n";
        echo $this->headLink() . "\n";
        echo $this->headScript() . "\n";
        echo $this->headMeta() . "\n";
        ?>
    </head>
    <body>
        <div style="width:760px;margin:0px auto;">
            <h1>THE GAME</h1>
            <div style="text-align: center;">
            <?php echo $this->layout()->content; ?>
            </div>
        </div>
    </body>
</html>