<?php echo $this->doctype() ?>
<html>
    <head>        
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">        
        <?php
        echo $this->headTitle() . "\n";
        echo $this->headLink() . "\n";
        echo $this->headScript() . "\n";
        echo $this->headMeta() . "\n";
        ?>
    </head>
    <body>
        <div id="page">
            <?php echo $this->layout()->content; ?>
        </div>
    </body>
</html>