<?php
$urlStart = '';
?>
<p>Maximum allowed number of players: "<?php echo $this->game['numberOfPlayers'] ?>"</p>
<h4>Players in game</h4>
<table id="playersingame">
<th>Player Id</th><th>Ready</th>
<?php
for($i = 0; $i < $this->game['numberOfPlayers']; $i++) {
    echo '<tr id="'.$this->colors[$i].'"><td id="td1"></td><td id="td2"><a href="javascript:playerReady('.$i.')"></a></td></tr>';
}
?>
</table>
<h4>Players out</h4>
<table id="playersout"></table>

<ul>
    <li><a class="button" href="<?php echo $this->url(array('controller' => 'gamesetup', 'action' => 'index', 'gameId' => null)) ?>">< Back</a></li>
    <li><a class="button" href="javascript:refresh()">Refresh</a></li>
    <li id="start">
        <?php
        if ($this->game['gameMasterId'] == $this->player['playerId']) {
            $urlStart = $this->url(array('controller' => 'gamesetupajax', 'action' => 'gamestart', 'gameId' => null));
        }
        ?>
    </li>
</ul>
<script type="text/javascript">
    var th = '<th>Player Id</th>';
    var url = '<?php echo $this->url(array('controller' => 'gamesetup', 'action' => 'setup')) ?>';
    var urlStart = '<?php echo $urlStart; ?>';
    var urlRedirect = '<?php echo $this->url(array('controller' => 'gamesetup', 'action' => 'start', 'gameId' => null)); ?>';
    var urlReady = '<?php echo $this->url(array('controller' => 'gamesetupajax', 'action' => 'ready', 'gameId' => null)) ?>';
    var urlAjax = '<?php echo $this->url(array('controller' => 'gamesetupajax', 'action' => 'setuprefresh', 'gameId' => null)) ?>';
    var numberOfPlayers = <?php echo (int) $this->game['numberOfPlayers'] ?>;
    var ready = '<?php echo $this->player['ready'] ?>';
    var colors = <?php echo Zend_Json::encode($this->colors) ?>;
    var playerId = <?php echo (int) $this->player['playerId'] ?>;

<?php if ($urlStart) { ?>
    function start() {
        $.getJSON(urlStart, function(result) {
            $('#start').html('');
        });
    }
<?php } ?>
</script>
