<h1>New game</h1>

<h1>Waiting for other players</h1>

<script type="text/javascript">
    function refresh() {
        $.getJSON('/en/gamesetupajax/allarmiesready', function (result) {
            if (result.all) {
                top.location.assign('/<?php echo  Zend_Registry::get('lang') ?>/game');
            }
        });
    }
    $(document).ready(function () {
        setInterval('refresh()', 5000);
    });

</script>
